{"name": "test_order_track_wrong_order_id_fail", "status": "passed", "description": "Получаем данные о заказе с несуществующим номером", "start": 1699369412815, "stop": 1699369412937, "uuid": "3a38f80f-93a3-43f5-89f5-4d7eb3119888", "historyId": "0670e0e84089c2671e5cc15e16c53cfb", "testCaseId": "0670e0e84089c2671e5cc15e16c53cfb", "fullName": "tests.test_order.TestTrackOrder#test_order_track_wrong_order_id_fail", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_order"}, {"name": "subSuite", "value": "TestTrackOrder"}, {"name": "host", "value": "i101922157"}, {"name": "thread", "value": "18296-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_order"}]}