{"name": "test_courier_create_already_existing_user_fail", "status": "passed", "description": "Проверяем создание курьера с использованием уже существующих данных", "start": 1699369349223, "stop": 1699369349300, "uuid": "d4c392ee-a91b-4412-8cea-9a0d1322f0a2", "historyId": "e835cf87a241f60fbedccf5582cad2c6", "testCaseId": "e835cf87a241f60fbedccf5582cad2c6", "fullName": "tests.test_courier.TestCourierCreateAPI#test_courier_create_already_existing_user_fail", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier"}, {"name": "subSuite", "value": "TestCourierCreateAPI"}, {"name": "host", "value": "i101922157"}, {"name": "thread", "value": "18296-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier"}]}