{"name": "test_courier_login_no_data_fail[user_data0]", "status": "passed", "description": "Проверяем попытку входа с отправкой недостаточных данных", "parameters": [{"name": "user_data", "value": "{'login': '', 'password': 'test_password!'}"}], "start": 1699369265021, "stop": 1699369265092, "uuid": "f01a4795-dea1-4f5c-be2e-7429226bd09b", "historyId": "6bb29792b2878bb774e8f7d979921615", "testCaseId": "9d10fbc3585789bb29ad092d3d064fa0", "fullName": "tests.test_courier.TestCourierLoginAPI#test_courier_login_no_data_fail", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier"}, {"name": "subSuite", "value": "TestCourierLoginAPI"}, {"name": "host", "value": "i101922157"}, {"name": "thread", "value": "17436-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier"}]}