{"name": "test_courier_login_no_data_fail[user_data2]", "status": "passed", "description": "Проверяем попытку входа с отправкой недостаточных данных", "parameters": [{"name": "user_data", "value": "{'password': 'test_password!'}"}], "start": 1699369350780, "stop": 1699369350840, "uuid": "c1af49dc-38a4-426c-82cf-4d02759221b2", "historyId": "50ac81c54a4b090cae583679d592a20d", "testCaseId": "9d10fbc3585789bb29ad092d3d064fa0", "fullName": "tests.test_courier.TestCourierLoginAPI#test_courier_login_no_data_fail", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier"}, {"name": "subSuite", "value": "TestCourierLoginAPI"}, {"name": "host", "value": "i101922157"}, {"name": "thread", "value": "18296-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier"}]}