{"name": "test_courier_login_no_data_fail[user_data1]", "status": "passed", "description": "Проверяем попытку входа с отправкой недостаточных данных", "parameters": [{"name": "user_data", "value": "{'login': 'test_login_1789', 'password': ''}"}], "start": 1699369350682, "stop": 1699369350773, "uuid": "bb807868-9e2a-46fb-8102-d547580570c6", "historyId": "b4c0992161d0158ea9ab4229f89c9305", "testCaseId": "9d10fbc3585789bb29ad092d3d064fa0", "fullName": "tests.test_courier.TestCourierLoginAPI#test_courier_login_no_data_fail", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier"}, {"name": "subSuite", "value": "TestCourierLoginAPI"}, {"name": "host", "value": "i101922157"}, {"name": "thread", "value": "18296-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier"}]}