{"name": "test_courier_create_already_existing_user_fail", "status": "passed", "description": "Проверяем создание курьера с использованием уже существующих данных", "start": 1699369263728, "stop": 1699369263810, "uuid": "650e6d1d-addc-4fce-bf47-95e9ed0f44be", "historyId": "e835cf87a241f60fbedccf5582cad2c6", "testCaseId": "e835cf87a241f60fbedccf5582cad2c6", "fullName": "tests.test_courier.TestCourierCreateAPI#test_courier_create_already_existing_user_fail", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier"}, {"name": "subSuite", "value": "TestCourierCreateAPI"}, {"name": "host", "value": "i101922157"}, {"name": "thread", "value": "17436-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier"}]}