{"name": "test_courier_login_no_data_fail[user_data0]", "status": "passed", "description": "Проверяем попытку входа с отправкой недостаточных данных", "parameters": [{"name": "user_data", "value": "{'login': '', 'password': 'test_password!'}"}], "start": 1699369350561, "stop": 1699369350676, "uuid": "47e57c4e-fb7e-404d-91d5-fcb27ca1ffa3", "historyId": "6bb29792b2878bb774e8f7d979921615", "testCaseId": "9d10fbc3585789bb29ad092d3d064fa0", "fullName": "tests.test_courier.TestCourierLoginAPI#test_courier_login_no_data_fail", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier"}, {"name": "subSuite", "value": "TestCourierLoginAPI"}, {"name": "host", "value": "i101922157"}, {"name": "thread", "value": "18296-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier"}]}